### ISSUE TITLE
Expand the library of transform functions for simple objects

### ISSUE THREAD

**Issue by p013570** [gchq/koryphe#172]
Functions, such as:
- StringReverse
- StringReplace (provide a pattern and it replaces all occurrences)
- StringTruncate (extracts the first X characters of a String. Optionally replaces the rest with '...').
- StringTrim (trims a string - StringUtils.trim)
- StringSplit (String.split - and converts the output array to an ArrayList. Initialised with the regex pattern for splitting)
- StringAppend (Initialised with a suffix string. Takes an input and appends the suffix to it.
- StringPrepend (Initialised with a prefix string. Takes an input and prepends the prefix to it.
- DefaultIfNull
- DefaultIfEmpty (this could delegate to the Koryphe Length function)
- StringJoin (join an iterable or array with a provided delimiter and output a string)
- Longest (takes 2 objects, applies the Koryphe Length function and returns the longest)
- IterableLongest (takes an iterable of objects, applies the Koryphe Length function and returns the longest)
- IterableFlatten (takes an iterable of objects and applies a provided BinaryOperator to all objects and returns the flattened result)
- FirstValid (takes an iterable of objects and returns the first one that a provided predicate returns true for)
- LookupValueInMap (initialised with a Map. Takes an object, looks it up in the map and returns the value from the map)
- MultiplyLongBy (same as the Koryphe MultiplyBy function for but Longs. We can't change the existing MultiplyBy function so we need up create a separate one)

Some of these functions could just delegate to StringUtils in the apache commons library. There could be some other functions within StringUtils or other utils in apache commons that might also be worth exposing.

**Comment by p013570** [comment]
I will be working on this on and off for the next couple of months.

**Comment by p013570** [comment]
Working on branch gh-172-functions

**Comment by c95560** [comment]
Would it make sense to modify the CallMethod function to take parameters? It would expose a lot of transform functions via standard Java implementations.

**Comment by p013570** [comment]
@c95560 - that would be useful. Perhaps we could make that change in a separate ticket?

**Comment by d47853** [comment]
Merged into devlop
