### ISSUE TITLE
Build fails with Maven 3.6.3

### ISSUE THREAD

**Issue by flitte** [gchq/koryphe#175]
Hi all,

I'm attempting to build koryphe using Maven 3.6.3 and I'm seeing the following error:

`[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs (findbugs) on project koryphe: Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]`

Updating the findbugs plugin version from 3.0.3 to 3.0.5 (latest) fixes the issue.

**Comment by d47853** [comment]
Merged into develop
