### ISSUE TITLE
Generate a valid Signature for ApplyBiFunction 

### ISSUE THREAD

**Issue by m29827** [gchq/koryphe#180]
The ApplyBiFunction is used to wrap a BiFunction implementation which is executed at runtime and it's not currently possible to generate a valid Signature for this function using the existing logic.  The Type Parameters declared in ApplyBiFunction need to be mapped through to the Types contained in the wrapped BiFunction to create a valid Signature and enable type checking of parameters to be enforced. See [gh-2268](https://github.com/gchq/Gaffer/issues/2268)

**Comment by d47853** [comment]
Merged into develop
