### ISSUE TITLE
Improve input and output Signature generation 

### ISSUE THREAD

**Issue by m29827** [gchq/koryphe#184]
The input and output signatures generated by `uk.gov.gchq.koryphe.signature.Signature` do not handle `uk.gov.gchq.koryphe.tuple.Tuple` implementations optimally in all cases.  The code should only attempt to generate a `uk.gov.gchq.koryphe.signature.TupleSignature` for implementations of `uk.gov.gchq.koryphe.tuple.n.TupleN` where a known and parameterised number of items will be present in the Tuple.  In this case the Type parameters of the Tuple may be interrogated and the list of expected classes generated, otherwise the code should fall back to a `uk.gov.gchq.koryphe.signature.SingletonSignature` containing the class implementing the Tuple.

In addition to this the approach taken to deriving Signatures starting from the parameters on the Function or Predicate class is not always yielding the expected results, a better approach would be to start with the parameters expected by the FunctionalInterface method.

**Comment by d47853** [comment]
Merged into develop

**Comment by d47853** [comment]
This was change was reverted as it caused breaking changes in downstream projects

**Comment by d47853** [comment]
Merged into develop
