### ISSUE TITLE
Upgrade JUnit version from 4 to 5

### ISSUE THREAD

**Issue by t11947** [gchq/koryphe#188]
Upgrading the version of JUnit will allow us to leverage the new features of JUnit 5 and use a version that is still being actively supported. This will also keep Koryphe in line with other Gaffer-related projects. Related issue here: https://github.com/gchq/Gaffer/issues/2270

**Comment by macenturalxl1** [comment]
Hi - please can I claim this one.

I've made a start and found two conflicting tests in `ExtractValueTest`
# 1 
```
    @Test
    public void shouldThrowExceptionForNullInput() {
        // Given
        final ExtractValue<String, Integer> function = new ExtractValue<>();

        // When / Then
        try {
            final Integer result = function.apply(null);
        } catch (final IllegalArgumentException e) {
            assertTrue(e.getMessage().contains("Input cannot be null"));
        }
    }
```
# 2
```
    @Test
    public void shouldThrowExceptionForEmptyInput() {
        // Given
        final ExtractValue<String, Integer> function = new ExtractValue<>();
        final Map<String, Integer> input = null;

        // When
        final Integer result = function.apply(input);

        // Then
        assertNull(result);
    }
```
In 1, the implementation doesn't throw an IAX and doesn't have a _fail()_ (as you can see in 2 it would pass).

Would you like it to throw an IAX for a null input (the other Functions don't)  - or delete the test 1 as test 2 is the correct behaviour?

**Comment by t11947** [comment]
Delete test 1 please. Good spot.

**Comment by macenturalxl1** [comment]
> Delete test 1 please. Good spot.

Thank you - done

**Comment by d47853** [comment]
Merged into develop
