### ISSUE TITLE
ToUpperCase and ToLowerCase ignore return value when value is of type String

### ISSUE THREAD

**Issue by lucean** [gchq/koryphe#189]
ToLowerCase and ToUpperCase both ignore the calculated value if the input value is already a String:

```java
if (value instanceof String) {
    StringUtils.lowerCase((String) value);
}
```

This block should be removed or the calculated value should be returned.

**Comment by d47853** [comment]
Thanks for spotting that @lucean. We'll get that sorted for the next release

**Comment by d47853** [comment]
Merged into develop
