### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by t11947** [gchq/koryphe#194]
Upgrading Koryphe to Java 11 will allow us to keep up with the Java LTS version and leverage some of the new features in post-Java 8 versions such as better integration with container technologies, the JShell and new language features.

Modularisation of Koryphe is not in scope for this ticket. A new ticket will be raised for this once the upgrade has occurred.

Related to Gaffer issue: https://github.com/gchq/gaffer/issues/2300

**Comment by n3101** [comment]
PR #196 was applied and then reverted as being a breaking change. The PR has been closed but I don't think it was ever applied to the v2_develop branch, which is where it belongs. This needs checking.
