### ISSUE TITLE
Add ToDouble function

### ISSUE THREAD

**Issue by p3430233** [gchq/koryphe#235]

**Comment by n3101** [comment]
@p3430233 from what?

**Comment by t92549** [comment]
There is a missing koryphe function required by https://github.com/gchq/Gaffer/pull/2550

**Comment by n3101** [comment]
@t92549 ok - so converting what sort of object to a double ? (int, float, what?)

**Comment by t92549** [comment]
It should be very similar to [ToLong](https://github.com/gchq/koryphe/blob/develop/core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToLong.java), taking an object and trying to turn it into a Double. There are also maybe more functions that should be added.
