### ISSUE TITLE
ChainedIterable Duplicate Class

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/koryphe#266]
linked to : [ChainedIterable Duplicated Classes. #2369](https://github.com/gchq/Gaffer/issues/2369)

Make ChainedIterable public

**Comment by t92549** [comment]
To fix the issue of duplicating the ChainedIterable class between koryphe and Gaffer, they should be made public in koryhpe. Then they can be removed from Gaffer, replacing all Gaffer references to the public koryphe version: https://github.com/gchq/Gaffer/issues/2369.
