### ISSUE TITLE
Add option to AreIn to perform a strict test and return false if the collection is null or empty

### ISSUE THREAD

**Issue by n3101** [gchq/koryphe#280]
AreIn tests whether supplied values are all in a given collection, but also returns true if the collection is null or empty. This behaviour was intended - it is tested for and documented. The rationale for this has been lost.

Retain this as the default behaviour, but add an option to perform the strict test and return false if null or empty

**Comment by shlokam** [comment]
@n3101 @t92549 Can you assign this issue to me?

**Comment by n3101** [comment]
@shlokam I certainly can. Welcome!
