### ISSUE TITLE
Fix broken Crown Copyright link

### ISSUE THREAD

**Issue by t11947** [gchq/koryphe#281]
The link to the National Archives page describing Crown Copyright is broken on the readme. Update it to point here:
https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/

**Comment by Mannuel25** [comment]
Hello @t11947 , I'd like to take this up. Kindly assign it to me.

**Comment by t92549** [comment]
> Hello @t11947 , I'd like to take this up. Kindly assign it to me.

Sorry we never got back to you, would you still like to be assigned?

**Comment by Mannuel25** [comment]
Yeah, I'm still up for it. Thanks
