### ISSUE TITLE
NullPointerException in CollectionContains

### ISSUE THREAD

**Issue by t92549** [gchq/koryphe#283]
If input is null, this will error rather than return false:
https://github.com/gchq/koryphe/blob/8f0458806f9e534d1bd5ab9c44920f100fa7d12e/core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/CollectionContains.java#L57-L58

**Comment by derlin** [comment]
Hello there ! is this just about implementing the fix in this function ? I am interested !

**Comment by derlin** [comment]
If you don't mind, may I kindly ask you to add the label  [hacktoberfest-accepted](https://hacktoberfest.com/participation/#pr-mr-details) to the PR ?
You may refuse of course, I am glad to contribute anyway :)

**Comment by t92549** [comment]
Thanks a lot for the contribution! I will add the tag now as the fix is good
