### ISSUE TITLE
Fix typos in ToSetTest and AdaptedBinaryOperatorTest

### ISSUE THREAD

**Issue by t92549** [gchq/koryphe#289]
https://github.com/gchq/koryphe/blob/152f8a9fa88f8998cfc1f7dc090dd3ca6f5dea45/core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToSetTest.java#L34
https://github.com/gchq/koryphe/blob/152f8a9fa88f8998cfc1f7dc090dd3ca6f5dea45/core/src/test/java/uk/gov/gchq/koryphe/binaryoperator/AdaptedBinaryOperatorTest.java#L120
Both lines end in `;;` rather than `;`

**Comment by shlokam** [comment]
@t92549 could you assign this to me?

**Comment by shlokam** [comment]
@t92549 Can you add the label hacktoberfest to the repository?

**Comment by t92549** [comment]
I have added hacktoberfest-accepted to the PR, that should do it?

**Comment by shlokam** [comment]
Yes, thank you.
