### ISSUE TITLE
Fix license typo in ToNullTest

### ISSUE THREAD

**Issue by t92549** [gchq/koryphe#291]
https://github.com/gchq/koryphe/blob/152f8a9fa88f8998cfc1f7dc090dd3ca6f5dea45/core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToNullTest.java#L1-L5
In ToNullTest the package line comes before the license rather than after, like the other files

**Comment by GCHQDeveloper314** [comment]
Making any change to this file will cause spotless to pick up on this. Running it with different settings will allow it to suggest the correction I think.

**Comment by ismacarbo** [comment]
gg
