### ISSUE TITLE
Create a StringDeduplicateConcat BinaryOperator

### ISSUE THREAD

**Issue by p013570** [gchq/koryphe#35]
Ideally we would just change the StringConcat binary operator, but that could cause issues for anyone using it, so instead we should just create a new StringDeduplicateConcat.

This should be based on the current StringConcat, but instead of just concatenating the strings together we should deduplicate the values.

For example:

1 + 2 -> 1,2
1,2 + 3 -> 1,2,3
1,2,3 + 2 -> 1,2,3    NOT 1,2,3,2
1,2,3 + 1,2 -> 1,2,3
1,2,3 + 1,2,4 -> 1,2,4

It would be more efficient for users to use a Set and a SetBinaryOperator but in some cases using a String property might be required.

**Comment by m607123** [comment]
Just for some clarification, is the order of the delimited substrings to be preserved upon concat?
For example, should:
2 + 1 -> 1,2 or 2,1?
Also, should:
1,2,4 + 1,2,3 -> 1,2,3,4 or 1,2,4,3?

**Comment by p013570** [comment]
Merged into develop.
