### ISSUE TITLE
Should be easier to extract initial seeds from a GetWalks operation

### ISSUE THREAD

**Issue by m607123** [gchq/koryphe#74]
Currently the method by which the initial seeds are extracted from a GetWalks implementation is quite nested, requiring multiple operations and functions to achieve.

As a suggestion from @p013570, now that Entities are also returned from a GetWalks operation, this process could be simplified and possibly improved by the addition of a further function, namely ExtractValue, which, from a Java map, pulls out the value for a provided key.

**Comment by p013570** [comment]
Merged into develop.
